// Auto-generated by buffela-to-types, DO NOT MODIFY

import type calf from "@buffela/parser/internal/Calf"
type ValueOf<T extends object> = T[keyof T]

type schema = {
    readonly Gender : {
        readonly FEMALE: unique symbol
        readonly MALE: unique symbol
    }

    readonly TokenPayload : calf<TokenPayload> & {
        readonly Anonymous: unique symbol

        readonly Registered : {
            readonly Phone: unique symbol
            readonly Email: unique symbol
        }
        readonly Organizer: unique symbol
    }

    readonly Token : calf<Token> & {}
}

export default schema

export type Gender = ValueOf<schema["Gender"]>

export type TokenPayload = {
    userId: Buffer,
} & (
    {
        role: schema["TokenPayload"]["Anonymous"],
    } | {
        role: schema["TokenPayload"]["Registered"],
        gender: Gender,
        hobbies: string[],
    } & (
        {
            with: schema["TokenPayload"]["Registered"]["Phone"],
            phone: string,
        } | {
            with: schema["TokenPayload"]["Registered"]["Email"],
            email: string,
        }
    ) | {
        role: schema["TokenPayload"]["Organizer"],
        email: string,
    }
)

export type Token = {
    expiration: number,
    signature: Buffer,
    payload: TokenPayload,
    version?: never,
}
