// Auto-generated by buffela-to-kotlin, DO NOT MODIFY

import kotlinx.io.writeDoubleLe
import kotlinx.io.writeFloatLe
import kotlinx.io.writeUByte
import kotlinx.io.writeUIntLe
import kotlinx.io.writeULongLe
import kotlinx.io.writeUShortLe
import gr.elaevents.buffela.internal.utils.writeStringNt

import kotlinx.io.readDoubleLe
import kotlinx.io.readFloatLe
import kotlinx.io.readUByte
import kotlinx.io.readUIntLe
import kotlinx.io.readULongLe
import kotlinx.io.readUShortLe
import kotlinx.io.readByteArray
import gr.elaevents.buffela.internal.utils.readStringNt

enum class Gender {
    FEMALE,
    MALE,
}

sealed class TokenPayload: gr.elaevents.buffela.schema.Serializable {
    val userId: ByteArray

    constructor(
        userId: ByteArray,
    ): super() {
        this.userId = userId
    }

    override fun serializeHeader(packet: kotlinx.io.Buffer) {
        packet.writeUByte(_leafIndex)
    }

    override fun serializeBody(packet: kotlinx.io.Buffer) {
        packet.write(this.userId)
    }

    protected constructor(packet: kotlinx.io.Buffer): super() {
        this.userId = packet.readByteArray(16)
    }

    companion object Deserializer {
        private fun validateHeader(packet: kotlinx.io.Buffer) {}

        fun deserialize(packet: kotlinx.io.Buffer): TokenPayload {
            validateHeader(packet)

            return when(packet.readUByte().toInt()) {
                0 -> Anonymous.deserialize(packet)
                1 -> Registered.Phone.deserialize(packet)
                2 -> Registered.Email.deserialize(packet)
                3 -> Organizer.deserialize(packet)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }

    final class Anonymous: TokenPayload {
        constructor(
            userId: ByteArray,
        ): super(
            userId,
        ) {}
        override val _leafIndex: UByte = 0u

        override fun serializeHeader(packet: kotlinx.io.Buffer) {
            super.serializeHeader(packet)
        }

        override fun serializeBody(packet: kotlinx.io.Buffer) {
            super.serializeBody(packet)
        }

        private constructor(packet: kotlinx.io.Buffer): super(packet) {}

        internal companion object Deserializer {
            private fun validateHeader(packet: kotlinx.io.Buffer) {}

            fun deserialize(packet: kotlinx.io.Buffer): Anonymous {
                validateHeader(packet)
                return Anonymous(packet)
            }
        }
    }

    sealed class Registered: TokenPayload {
        val gender: Gender
        val hobbies: Array<String>

        constructor(
            userId: ByteArray,
            gender: Gender,
            hobbies: Array<String>,
        ): super(
            userId,
        ) {
            this.gender = gender
            this.hobbies = hobbies
        }

        override fun serializeHeader(packet: kotlinx.io.Buffer) {
            super.serializeHeader(packet)
        }

        override fun serializeBody(packet: kotlinx.io.Buffer) {
            super.serializeBody(packet)
            packet.writeUByte(this.gender.ordinal.toUByte())
            packet.writeUByte(this.hobbies.size.toUByte())

            for (item1 in this.hobbies) {
                packet.writeStringNt(item1)
            }
        }

        protected constructor(packet: kotlinx.io.Buffer): super(packet) {
            this.gender = Gender.entries[packet.readUByte().toInt()]
            this.hobbies = Array(packet.readUByte().toInt()) { _ -> packet.readStringNt() }
        }

        internal companion object Deserializer {
            protected fun validateHeader(packet: kotlinx.io.Buffer) {}
        }

        final class Phone: Registered {
            val phone: String

            constructor(
                userId: ByteArray,
                gender: Gender,
                hobbies: Array<String>,
                phone: String,
            ): super(
                userId,
                gender,
                hobbies,
            ) {
                this.phone = phone
            }
            override val _leafIndex: UByte = 1u

            override fun serializeHeader(packet: kotlinx.io.Buffer) {
                super.serializeHeader(packet)
            }

            override fun serializeBody(packet: kotlinx.io.Buffer) {
                super.serializeBody(packet)
                packet.writeStringNt(this.phone)
            }

            private constructor(packet: kotlinx.io.Buffer): super(packet) {
                this.phone = packet.readStringNt()
            }

            internal companion object Deserializer {
                private fun validateHeader(packet: kotlinx.io.Buffer) {
                    Registered.validateHeader(packet)
                }

                fun deserialize(packet: kotlinx.io.Buffer): Phone {
                    validateHeader(packet)
                    return Phone(packet)
                }
            }
        }

        final class Email: Registered {
            val email: String

            constructor(
                userId: ByteArray,
                gender: Gender,
                hobbies: Array<String>,
                email: String,
            ): super(
                userId,
                gender,
                hobbies,
            ) {
                this.email = email
            }
            override val _leafIndex: UByte = 2u

            override fun serializeHeader(packet: kotlinx.io.Buffer) {
                super.serializeHeader(packet)
            }

            override fun serializeBody(packet: kotlinx.io.Buffer) {
                super.serializeBody(packet)
                packet.writeStringNt(this.email)
            }

            private constructor(packet: kotlinx.io.Buffer): super(packet) {
                this.email = packet.readStringNt()
            }

            internal companion object Deserializer {
                private fun validateHeader(packet: kotlinx.io.Buffer) {
                    Registered.validateHeader(packet)
                }

                fun deserialize(packet: kotlinx.io.Buffer): Email {
                    validateHeader(packet)
                    return Email(packet)
                }
            }
        }
    }

    final class Organizer: TokenPayload {
        val email: String

        constructor(
            userId: ByteArray,
            email: String,
        ): super(
            userId,
        ) {
            this.email = email
        }
        override val _leafIndex: UByte = 3u

        override fun serializeHeader(packet: kotlinx.io.Buffer) {
            super.serializeHeader(packet)
        }

        override fun serializeBody(packet: kotlinx.io.Buffer) {
            super.serializeBody(packet)
            packet.writeStringNt(this.email)
        }

        private constructor(packet: kotlinx.io.Buffer): super(packet) {
            this.email = packet.readStringNt()
        }

        internal companion object Deserializer {
            private fun validateHeader(packet: kotlinx.io.Buffer) {}

            fun deserialize(packet: kotlinx.io.Buffer): Organizer {
                validateHeader(packet)
                return Organizer(packet)
            }
        }
    }
}

final class Token: gr.elaevents.buffela.schema.Serializable {
    val expiration: Double
    val signature: ByteArray
    val payload: TokenPayload

    constructor(
        expiration: Double,
        signature: ByteArray,
        payload: TokenPayload,
    ): super() {
        this.expiration = expiration
        this.signature = signature
        this.payload = payload
    }
    override val _leafIndex: UByte = 0u

    override fun serializeHeader(packet: kotlinx.io.Buffer) {
        packet.writeUByte(1u)
    }

    override fun serializeBody(packet: kotlinx.io.Buffer) {
        packet.writeDoubleLe(this.expiration)
        packet.write(this.signature)
        this.payload.serialize(packet)
    }

    private constructor(packet: kotlinx.io.Buffer): super() {
        this.expiration = packet.readDoubleLe()
        this.signature = packet.readByteArray(32)
        this.payload = TokenPayload.deserialize(packet)
    }

    companion object Deserializer {
        private fun validateHeader(packet: kotlinx.io.Buffer) {
            if (
                packet.readUByte() != 1u.toUByte()
            ) throw IllegalStateException("Incompatible packet version")
        }

        fun deserialize(packet: kotlinx.io.Buffer): Token {
            validateHeader(packet)
            return Token(packet)
        }
    }
}
