// Auto-generated by buffela-to-kotlin, DO NOT MODIFY
package gr.elaevents.buffela.examples.simple

import kotlinx.io.writeDoubleLe
import kotlinx.io.writeFloatLe
import kotlinx.io.writeUByte
import kotlinx.io.writeUIntLe
import kotlinx.io.writeULongLe
import kotlinx.io.writeUShortLe
import gr.elaevents.buffela.internal.utils.writeStringNt

import kotlinx.io.readDoubleLe
import kotlinx.io.readFloatLe
import kotlinx.io.readUByte
import kotlinx.io.readUIntLe
import kotlinx.io.readULongLe
import kotlinx.io.readUShortLe
import kotlinx.io.readByteArray
import gr.elaevents.buffela.internal.utils.readStringNt

enum class Gender {
    FEMALE,
    MALE,
}

sealed class User: gr.elaevents.buffela.schema.Serializable {
    val userId: String
    val gender: Gender
    val hobbies: Array<String>

    constructor(
        userId: String,
        gender: Gender,
        hobbies: Array<String>,
    ): super() {
        this.userId = userId
        this.gender = gender
        this.hobbies = hobbies
    }

    override fun serialize(packet: kotlinx.io.Sink) {}

    companion object Deserializer {
        fun deserialize(packet: kotlinx.io.Source): User {
            return when(packet.readUByte().toInt()) {
                0 -> RegisteredWithPhone.deserialize(packet)
                1 -> RegisteredWithEmail.deserialize(packet)
                else -> throw IllegalStateException("Invalid subtype index")
            }
        }
    }

    final class RegisteredWithPhone: User {
        val countryCode: UByte
        val phone: String

        constructor(
            userId: String,
            gender: Gender,
            hobbies: Array<String>,
            countryCode: UByte,
            phone: String,
        ): super(
            userId,
            gender,
            hobbies,
        ) {
            this.countryCode = countryCode
            this.phone = phone
        }

        override fun serialize(packet: kotlinx.io.Sink) {
            super.serialize(packet)
            packet.writeUByte(0u)
            packet.writeUByte(this.countryCode)
            packet.writeStringNt(this.phone)
            packet.writeStringNt(this.userId)
            packet.writeUByte(this.gender.ordinal.toUByte())
            packet.writeUByte(this.hobbies.size.toUByte())

            for (item1 in this.hobbies) {
                packet.writeStringNt(item1)
            }
        }

        private constructor(packet: kotlinx.io.Source): this(
            countryCode = packet.readUByte(),
            phone = packet.readStringNt(),
            userId = packet.readStringNt(),
            gender = Gender.entries[packet.readUByte().toInt()],
            hobbies = Array(packet.readUByte().toInt()) { _ -> packet.readStringNt() },
        )

        internal companion object Deserializer {
            fun deserialize(packet: kotlinx.io.Source): RegisteredWithPhone {
                return RegisteredWithPhone(packet)
            }
        }
    }

    final class RegisteredWithEmail: User {
        val email: String

        constructor(
            userId: String,
            gender: Gender,
            hobbies: Array<String>,
            email: String,
        ): super(
            userId,
            gender,
            hobbies,
        ) {
            this.email = email
        }

        override fun serialize(packet: kotlinx.io.Sink) {
            super.serialize(packet)
            packet.writeUByte(1u)
            packet.writeStringNt(this.email)
            packet.writeStringNt(this.userId)
            packet.writeUByte(this.gender.ordinal.toUByte())
            packet.writeUByte(this.hobbies.size.toUByte())

            for (item1 in this.hobbies) {
                packet.writeStringNt(item1)
            }
        }

        private constructor(packet: kotlinx.io.Source): this(
            email = packet.readStringNt(),
            userId = packet.readStringNt(),
            gender = Gender.entries[packet.readUByte().toInt()],
            hobbies = Array(packet.readUByte().toInt()) { _ -> packet.readStringNt() },
        )

        internal companion object Deserializer {
            fun deserialize(packet: kotlinx.io.Source): RegisteredWithEmail {
                return RegisteredWithEmail(packet)
            }
        }
    }
}

final class AuthToken: gr.elaevents.buffela.schema.Serializable {
    val issuedAt: Double
    val signature: ByteArray
    val user: User

    constructor(
        issuedAt: Double,
        signature: ByteArray,
        user: User,
    ): super() {
        this.issuedAt = issuedAt
        this.signature = signature
        this.user = user
    }

    override fun serialize(packet: kotlinx.io.Sink) {
        packet.writeUByte(1u)
        packet.writeDoubleLe(this.issuedAt)
        packet.write(this.signature)
        this.user.serialize(packet)
    }

    private constructor(packet: kotlinx.io.Source): this(
        issuedAt = packet.readDoubleLe(),
        signature = packet.readByteArray(32),
        user = User.deserialize(packet),
    )

    companion object Deserializer {
        fun deserialize(packet: kotlinx.io.Source): AuthToken {
            if (
                packet.readUByte() != 1u.toUByte()
            ) throw IllegalStateException("Incompatible packet version")
            return AuthToken(packet)
        }
    }
}
